[package]
name = "babel_codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
query_parser = { version = "*", path = "../query_parser"}